on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Version
        run: |
          echo "::set-output name=commit_number::$(git rev-parse --short HEAD)"
          echo "::set-output name=version::$(grep -oE 'fw_version = [0-9]+' ./MM-control-01/version.h.in | grep -oE '[0-9]+')"
        id: build-version
      - name: Compile Firmware
        run: ./build.sh
      - name: Move Artifact
        run: mkdir -p dist; mv ../MM-control-01-build/MM-control-01.hex dist/MM-control-01_${{ steps.build-version.outputs.version }}_${{ steps.build-version.outputs.commit_number }}.hex
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MM-control-01_${{ steps.build-version.outputs.version }}_${{ steps.build-version.outputs.commit_number }}.hex
          path: dist